#
###################################
# Site wide configuration
####################################
#
title: Anqi's bolg
email: anqizuo1213@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Anqi Zuo
  avatar: angel1.png
  #job: "PHP & Ruby Developer"
  #bio: "A backend developer who loves design awesome things. Working for RendezvousCheznous atm in Marseille, France."
  #email: anqizuo1213@gmail.com
  #disqus-shortname: renyuanzblog
  #@twitter: renyuan814 #username
  #facebook: #username
  google:
    plus: #username
    analytics: # edit to insert your GA script
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kisumzzz #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  #linkedin:  Anqi(Angela) Zuo
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
